environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version

build: off

version: "{build}"
